---
title: "R Notebook"
output: html_notebook
---
```{r}
library("gamboostLSS")
library("R2BayesX")
library("tidyverse")
```

```{r}
data("india", package = "gamboostLSS")
data("india.bnd", package = "gamboostLSS")
neighborhood <- bnd2gra(india.bnd)
ctrl <- boost_control(trace = TRUE, mstop = c(mu = 100))
coef <- "mbmi"
kn <- 70
mn <- 1000
n <- 4000
```

 
```{r include=FALSE}
a <- variance_1kn(formula = stunting ~ bbs(mage) + bbs(mbmi) + bbs(cage) + bbs(cbmi) 
                    ,  data = india,
                    families = GaussianLSS(stabilization = "MAD"), control = ctrl, kn = kn, mn = mn, nz = 20, nMC = 100, coef = "mbmi")
```

```{r include=FALSE}
sub_boot <- subbagging(formula = stunting ~ bbs(mage) + bbs(mbmi) + bbs(cage) + bbs(cbmi) 
 ,  data = india,
families = GaussianLSS(stabilization = "MAD"), control = ctrl, kn = kn, mn = mn, coef = "mbmi")
sub_res = ci_predict(y_hat = sub_boot, alpha = 0.05)
```

```{r}

alpha <- n/mn
varian <-  (kn^2/mn) * (1/alpha) * a + (1/mn)*sub_res$variance_knkn #kn^2/alpha
```

```{r include=FALSE}
full_boot <- subbagging(formula = stunting ~ bbs(mage) + bbs(mbmi) + bbs(cage) + bbs(cbmi) 
 ,  data = india,
families = GaussianLSS(stabilization = "MAD"), control = ctrl, kn = 4000, mn = 50, coef = "mbmi")
res_full = ci_predict(y_hat = full_boot, alpha = 0.05)
```



```{r}
data <- india
coef <- "mbmi"
x <- seq(from = min(data[, coef]),to = max(data[, coef]), length = 100)
par(mfrow = c(1,2))
plot.gamboostLSS.ci(x = x, y =res_full[,1], x_obs = data$mbmi, sd =res_full[,2], lower = res_full[,3], upper = res_full[,4], ylim = c(-2, 2), alpha = 0.05)
plot.gamboostLSS.ci(x = x, y =sub_res[,1], x_obs = data$mbmi, sd =sqrt(varian), lower = sub_res[,3], upper = sub_res[,4], ylim = c(-2, 2), quant = FALSE, alpha = 0.05)

```
